// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFhlSHQ-xKRHxz_gKnmT0UnwAAxsavW-I',
    appId: '1:393498996591:web:bbb59bf55615bc3267c29a',
    messagingSenderId: '393498996591',
    projectId: 'ragam-music',
    authDomain: 'ragam-music.firebaseapp.com',
    storageBucket: 'ragam-music.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWRDfgDPGifs2jVcwNYomKUfukonjwgcs',
    appId: '1:393498996591:android:2fda5330291b133867c29a',
    messagingSenderId: '393498996591',
    projectId: 'ragam-music',
    storageBucket: 'ragam-music.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCOJjCOx2m4F-poC0_gyiIkNmXHh94usg',
    appId: '1:393498996591:ios:8d21a5e4870ef1d467c29a',
    messagingSenderId: '393498996591',
    projectId: 'ragam-music',
    storageBucket: 'ragam-music.appspot.com',
    iosBundleId: 'com.example.ragam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCOJjCOx2m4F-poC0_gyiIkNmXHh94usg',
    appId: '1:393498996591:ios:8d21a5e4870ef1d467c29a',
    messagingSenderId: '393498996591',
    projectId: 'ragam-music',
    storageBucket: 'ragam-music.appspot.com',
    iosBundleId: 'com.example.ragam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFhlSHQ-xKRHxz_gKnmT0UnwAAxsavW-I',
    appId: '1:393498996591:web:66c1fee8722252bb67c29a',
    messagingSenderId: '393498996591',
    projectId: 'ragam-music',
    authDomain: 'ragam-music.firebaseapp.com',
    storageBucket: 'ragam-music.appspot.com',
  );
}
